fix(deps): update module github.com/prometheus/client_golang to v1.19.0 (#84)
* fix(deps): update module github.com/prometheus/client_golang to v1.19.1
* stay in v1.19.0 because of: /go/pkg/mod/k8s.io/component-base@v0.30.2/metrics/testutil/metrics.go:73:59: undefined: expfmt.FmtText

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Thibault Richard <thb.krkr@gmail.com>